# Generated by Django 4.2.6 on 2023-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
