# Generated by Django 4.2.6 on 2023-12-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_alter_answer_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Answer",
            new_name="Choice",
        ),
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(default="Default Description"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="num_questions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
    ]
