# Generated by Django 4.2.6 on 2023-12-23 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_rename_answer_choice_quiz_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
