# Generated by Django 4.2.6 on 2023-12-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0010_rename_answer_text_answer_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="question_text",
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
    ]
