# Generated by Django 4.2.6 on 2023-12-23 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0012_alter_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
