# Generated by Django 4.2.6 on 2023-12-23 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0013_quiz_id_alter_quiz_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="id",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
