# Generated by Django 4.2.6 on 2023-12-24 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0015_alter_question_question_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
