# Generated by Django 4.2.6 on 2023-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdeaSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("text", models.TextField(blank=True)),
                (
                    "drawing_file",
                    models.FileField(blank=True, null=True, upload_to="drawing_files/"),
                ),
            ],
        ),
    ]
