# Generated by Django 4.2.6 on 2023-12-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to="blog_images/"),
        ),
    ]
